program:
  student:
    first_name: Gosha
    last_name: Alexandridi-Shandaevksiy
    middle_name: Dmitrievich
    group: IKBO-20-22
spring:
  datasource:
    url: ${URL}
    username: ${POSTGRES}
    password: ${PASSWORD}
#    url: jdbc:postgresql://localhost:5432/kursach
#    username: postgres
#    password: password
